version: "2"
services:
  labelimg:
     image: fpcasar/labelimg
     network_mode: host
     restart: always
     volumes:
        - /opt/vc:/opt/vc
        - /tmp/.X11-unix:/tmp/.X11-unix
     environment:
        LD_LIBRARY_PATH: /opt/vc/lib
        DISPLAY: :0.0
     devices:
        - "/dev/vchiq:/dev/vchiq"
     privileged: true
     command: ['tail', '-f', '/dev/null']
